branches:
  - master
  - main
  - "+([0-9])?(.{+([0-9]),x}).x"
  - name: alpha
    prerelease: alpha
  - name: beta
    prerelease: beta
plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/npm"
  - "@semantic-release/github"
