name: Assign Reviewer

on:
  pull_request:
    types: [opened, reopened, ready_for_review]

jobs:
  assign:
    runs-on: ubuntu-latest
    steps:
      - uses: hkusu/review-assign-action@v1
        with:
          reviewers: finlync-frontend-team
