name: Publish
on:
  push:
    branches: [dev]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - name: Print github context
      env:
        GITHUB_CONTEXT: ${{ toJSON(github) }}
      run: echo "$GITHUB_CONTEXT"
