name: Publish
on:
  push:
    branches: [dev]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 14
    - run: npm install -g @ui5/cli
    - run: npm version prerelease --preid beta
    - run: npm run build
    - run: npm publish --tag beta

    - name: Bump version
      uses: stefanzweifel/git-auto-commit-action@v4
