name: Publish deploy
on:
  push:
    branches: [deploy]

jobs:
  publish-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        path: repo-01
    - uses: actions/setup-node@v2
      with:
        node-version: 14
        registry-url: "https://npm.pkg.github.com"
    #- run: cd ./repo-01
    #- run: npm install -g @ui5/cli --ignore-scripts
    #- run: npm run build
    #  env:
    #    CI: true

    - name: Checkout tools repo
      uses: actions/checkout@v2
      with:
        repository: mauriciolauffer/github-action-test-02
        path: repo-02
    - run: ls .
    #- run: cd repo-01
    - run: cp -R ./src ../repo-02/
      working-directory: repo-01
    - run: ls ./repo-01/src
    - run: ls ./repo-02/
    - run: git config user.name "$GITHUB_ACTOR"
    - run: git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
    #- uses: stefanzweifel/git-auto-commit-action@v4
    #  with:
    #    commit_message: "ci: Build and publish BETA"

