name: Publish deploy
on:
  push:
    branches: [deploy]

jobs:
  publish-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        path: repo-01
    - uses: actions/setup-node@v2
      with:
        node-version: 14
        registry-url: "https://npm.pkg.github.com"
    - run: |
        npm install -g @ui5/cli --ignore-scripts
        npm run build
      working-directory: repo-01
      env:
        CI: true

    - name: Checkout tools repo
      uses: actions/checkout@v2
      with:
        repository: mauriciolauffer/github-action-test-02
        path: repo-02
        token: ${{ secrets.GIT_WRITE_TOKEN }}
    - run: rm -r ./distxxxxx/*
      working-directory: repo-02
    - run: rm -r ./dist/*
      working-directory: repo-02
    - run: |
        ls ../repo-02/
        cp -R ./dist ../repo-02/
      working-directory: repo-01
    - run: |
        git config user.name "$GITHUB_ACTOR"
        git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
        git add .
        git commit -m "ci: Build and publish BETA"
        git push
      working-directory: repo-02
