name: Publish Beta
on:
  push:
    branches: [dev]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 14
        registry-url: "https://npm.pkg.github.com"
    - run: git config --global user.name "$GITHUB_ACTOR"
    - run: git config --global user.email "$GITHUB_ACTOR@users.noreply.github.com"
    - run: npm install -g @ui5/cli --ignore-scripts
    - run: npm version prerelease --preid beta
    - run: npm run build
    - run: npm publish --tag beta
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "build: Build and publish BETA"
