name: Publish Beta
on:
  pull_request_review:
    branches: [dev]
    types: [submitted]

jobs:
  publish-dev:
    if: github.event.review.state == "approved"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 14
        registry-url: "https://npm.pkg.github.com"
    - run: git config user.name "$GITHUB_ACTOR"
    - run: git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
    - run: npm install -g @ui5/cli --ignore-scripts
    - run: npm version prerelease --preid beta
    - run: npm run build
    - run: npm publish --tag beta
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - run: git push
