name: Publish deploy
on:
  push:
    branches: [deploy]

jobs:
  publish-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 14
        registry-url: "https://npm.pkg.github.com"
    - run: npm install -g @ui5/cli --ignore-scripts
    - run: npm run build
      env:
        CI: true

