name: Release main
on:
  push:
    branches:
      - main

jobs:
  release-main:
    runs-on: ubuntu-latest
    steps:
      - uses: GoogleCloudPlatform/release-please-action@v2
        with:
          release-type: node
          package-name: github-action-test-01
