name: Release dev
on:
  push:
    branches:
      - dev

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: GoogleCloudPlatform/release-please-action@v2
        with:
          release-type: node
          package-name: github-action-test-01
