name: Test
on:
  pull_request:
  push:
    branches:
      - main
      - master
      - dev

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 14
    - run: npm install -g @ui5/cli
    - run: npm install
    - run: npm run build
    - run: npm run lint
      env:
        CI: true
